### ISSUE TITLE
Able to generate alphanumeric OTP token and the Token length should be configurable and able to configure validity time of the token. 

### ISSUE THREAD

**Issue by kesavany** [wso2-extensions/identity-outbound-auth-sms-otp#33]
**Description:**
Currently, SMSOTP authenticator only supports to generate 6 digit OTP token only. Need to add the feature to generate configurable length alphanumeric token with the configurable expiry time.

**Suggested Labels:**
New Feature

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Kanapriya** [comment]
Fixed this with following PR
